### ISSUE TITLE
Bug: Clicking right on the last story does not trigger all-stories-end event

### ISSUE THREAD

**Issue by dominikjohn** [dnldsht/vue-insta-stories#20]
Hi @dnldsht,
thank you for the amazing library! It was exactly what I was looking for.

I just noticed a small bug: When the user is at the last story and clicks on the right side, that does not trigger the all-stories-end event. So you have to wait for (in my case) 8 seconds until the last story has played out until the story end event is triggered. Do you know of a way around this or do you think you could find a way to fix this?

Thanks a lot in advance!

**Comment by dnldsht** [comment]
Hi! Which version of vue are you using?
Can you provide a simple reproduction example with stackbliz or a GitHub
repo so I can look into it?

**Comment by dnldsht** [comment]
@dominikjohn should work now in v0.9.6

**Comment by dominikjohn** [comment]
Hi @dnldsht, thank you for the quick reply and action! Unfortunately, it did not fix the problem for me – I have uploaded my Vue component here: https://github.com/dominikjohn/vue-insta-test/blob/main/ExerciseIntro.vue
The alert is not triggered when I click on the right side of the image while being at the last slide, it is only triggered when the story runs through by itself.

My vue version is 3.2.13.

Thanks in advance!

**Comment by dominikjohn** [comment]
For me the event has now stopped working entirely :/ it is not triggered by clicking or by waiting for the end of the story. Do I need to change something about my code?

**Comment by dominikjohn** [comment]
Hi @dnldsht, sorry for bothering you with this again – do you know of anything else I could try to make it work?

**Comment by dnldsht** [comment]
`@allStoryEnd` is emitted only when the stories ands without interaction. You can keep track of the `currentIndex` and `@next`to achieve it

### Props
| Property              | Type                  | Default  | Description                                                        |
|-----------------------|-----------------------|----------|--------------------------------------------------------------------|
| `stories`             | Array<String\|Object> | required | An array of image urls or array of story objects (more info below) |
| `interval`            | Number                | 2000     | Story duration in milliseconds                                     |
| `isPaused`            | Boolean               | false    | Toggle the playing state                                           |
| `loop`                | Boolean               | false    | Loop through stories                                               |
| `currentIndex`        | Number                | 0        | Set the current story index                                        |
| **Events**            |                       |          |                                                                    |
| `storyStart`          | Function(index)       | -        | Callback when a story starts                                       |
| `storyEnd`            | Function(index)       | -        | Callback when a story ends                                         |
| `allStoriesEnd`       | Function()            | -        | Callback when all stories have ended (not emitted if loop=true)    |
| `seeMore`             | Function(story)       | -        | Callback when user have pressed See more                           |
| `prev`                | Function()            | -        | Callback when user press prev                                      |
| `next`                | Function()            | -        | Callback when user press next                                      |
| `update:currentIndex` | Function(index)       | -        |                                                                    |
| `update:isPaused`     | Function(paused)      | -        |                                                                    |

**Comment by dominikjohn** [comment]
Thank you, that fixed it!
